apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: admin-service-config
spec:
  features:
    - name: SchedulerReminders
      enabled: false
  tracing:
    samplingRate: '1'
    zipkin:
      endpointAddress: 'http://localhost:9411/api/v2/spans'
  mtls:
    enabled: false
